ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 99

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "tower"
file = "C:/Users/wolfi/Documents/Python Playground/pixel-main/images/tower.png"
startx = 1650
starty = 427
priority = 2

[[structure]]
name = "gatech"
file = "C:/Users/wolfi/Documents/Python Playground/pixel-main/images/gatech.png"
startx = 379
starty = 528
priority = 2

[[structure]]
name = "pizzajohn"
file = "C:/Users/wolfi/Documents/Python Playground/pixel-main/images/pizzajohn.png"
startx = 1364
starty = 779
priority = 2

#[[structure]]
#name = "adler"
#file = "C:/Users/wolfi/Documents/Python Playground/pixel-main/images/adler.png"
#startx = 254
#starty = 830
#priority = 0